-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 07:52:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema venda de Produto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema venda de Produto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `venda de Produto` DEFAULT CHARACTER SET utf8 ;
USE `venda de Produto` ;

-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda de Produto`.`categorias` (
  `idcategorias` 		INT NOT NULL,
  `dscategoria` 		VARCHAR(45) NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda de Produto`.`produtos` (
  `idprodutos` 				INT NOT NULL,
  `dsproduto` 				VARCHAR(45) NOT NULL,
  `preco`				 	FLOAT NOT NULL,
  `qtdade` 					INT NOT NULL,
  `foto` 					LONGBLOB NOT NULL,
  `categorias_idcategorias` INT NOT NULL,
  PRIMARY KEY (`idprodutos`),
  -- INDEX `fk_produtos_categorias_idx` (`categorias_idcategorias` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_categorias`
    FOREIGN KEY (`categorias_idcategorias`)
    REFERENCES `venda de Produto`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda de Produto`.`clientes` (
  `idclientes` 			INT NOT NULL,
  `nome` VARCHAR(100) 	NOT NULL,
  `email` VARCHAR(100) 	NOT NULL,
  `senha` VARCHAR(100) 	NOT NULL,
  PRIMARY KEY (`idclientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda de Produto`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda de Produto`.`pedidos` (
  `idpedidos` 			INT NOT NULL,
  `data` 				DATE NOT NULL,
  `status` VARCHAR(45) 	NOT NULL,
  `sessao` VARCHAR(45) 	NOT NULL,
  `clientes_idclientes`	INT NOT NULL,
  PRIMARY KEY (`idpedidos`),
  -- INDEX `fk_pedidos_clientes1_idx` (`clientes_idclientes` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_clientes1`
    FOREIGN KEY (`clientes_idclientes`)
    REFERENCES `venda de Produto`.`clientes` (`idclientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda de Produto`.`pedidoitens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda de Produto`.`pedidoitens` (
  `idpedido itens` 			INT NOT NULL,
  `qtade` 					INT NOT NULL,
  `preco` 					FLOAT NOT NULL,
  `total` 					FLOAT NOT NULL,
  `produtos_idprodutos` 	INT NOT NULL,
  `pedidos_idpedidos` 		INT NOT NULL,
  PRIMARY KEY (`idpedido itens`),
  -- INDEX `fk_pedidoitens_produtos1_idx` (`produtos_idprodutos` ASC) VISIBLE,
  -- INDEX `fk_pedidoitens_pedidos1_idx` (`pedidos_idpedidos` ASC) VISIBLE,
  CONSTRAINT `fk_pedidoitens_produtos1`
    FOREIGN KEY (`produtos_idprodutos`)
    REFERENCES `venda de Produto`.`produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidoitens_pedidos1`
    FOREIGN KEY (`pedidos_idpedidos`)
    REFERENCES `venda de Produto`.`pedidos` (`idpedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
