-- MySQL Script generated by MySQL Workbench
-- Fri Sep 13 08:09:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema capacitacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema capacitacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `capacitacao` DEFAULT CHARACTER SET utf8 ;
USE `capacitacao` ;

-- -----------------------------------------------------
-- Table `capacitacao`.`Instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`Instrutor` (
  `id_Instrutor`           INT(11) NOT NULL,
  `Nome`                   VARCHAR(100) NOT NULL,
  `Email`                  VARCHAR(100) NOT NULL,
  `Valor_Hora`             DOUBLE NOT NULL,
  `Certificados`           VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_Instrutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capacitacao`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`Curso` (
  `id_Curso`               INT(11) NOT NULL,
  `Nome`                   VARCHAR(100) NOT NULL,
  `Requisito`              VARCHAR(100) NOT NULL,
  `Carga_Horaria`          DOUBLE NOT NULL,
  `Preço`                  DOUBLE NOT NULL,
  PRIMARY KEY (`id_Curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capacitacao`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`Turma` (
  `idTurma` 				INT(11) NOT NULL,
  `Carga_horaria` 			DOUBLE NOT NULL,
  `Data_inicial`		    DATE NOT NULL,
  `Data_Final` 				DATE NOT NULL,
  `Id_Instrutor` 			INT(11) NOT NULL,     -- Chave Estrangeira
  `Id_Curso` 				INT(11) NOT NULL,     -- Chave Estrangeira
  PRIMARY KEY (`idTurma`),
  -- INDEX `fk_Turma_Instrutor_idx` (`Id_Instrutor` ASC) VISIBLE,
  -- INDEX `fk_Turma_Curso1_idx` (`Id_Curso` ASC) VISIBLE,
  CONSTRAINT `fk_Turma_Instrutor`
    FOREIGN KEY (`Id_Instrutor`)
    REFERENCES `capacitacao`.`Instrutor` (`id_Instrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_Curso1`
    FOREIGN KEY (`Id_Curso`)
    REFERENCES `capacitacao`.`Curso` (`id_Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capacitacao`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`aluno` (
  `idaluno` 			INT NOT NULL,
  `Nome` 				VARCHAR(100) NOT NULL,
  `cpf`				 	VARCHAR(15) NOT NULL,
  `dataNasc` 			DATE NOT NULL,
  `telefone` 			CHAR(14) NOT NULL,
  `email` 				VARCHAR(100) NULL,
  PRIMARY KEY (`idaluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capacitacao`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capacitacao`.`matricula` (
  `Id_Matricula` 			INT(11) NOT NULL,
  `Data_Matricula` 			DATE NOT NULL,
  `Turma_idTurma` 			INT(11) NOT NULL,
  `aluno_idaluno` 			INT(11) NOT NULL,
  PRIMARY KEY (`Id_Matricula`),
  -- INDEX `fk_matricula_Turma1_idx` (`Turma_idTurma` ASC) VISIBLE,
  -- INDEX `fk_matricula_aluno1_idx` (`aluno_idaluno` ASC) VISIBLE,
  CONSTRAINT `fk_matricula_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `capacitacao`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `capacitacao`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
